### ISSUE TITLE
mod + period activaes the same mode as mod + p

### ISSUE THREAD

**Issue by indeedwatson** [piutranq/polybar-sxhkd#2]
I have a music mode that activates with `mod + p`, and a separate bind that's just `mod + period`.

I have tried variations such as:
`Hsuper +p: Music`
`Hsuper + p: Music`
`Hsuper + p : Music`

and modifying my sxhkdrc accordingly, but the problem persists.

**Comment by piutranq** [comment]
It was just a problem because the grep command finds all unnecessary hotkey that is including "$key"

I have just fixed line 54, "$key" -> "$key$", so the grep command will find the hotkey that is ending with "$key".

**Comment by indeedwatson** [comment]
Awesome, thanks!
